[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
aoc-client = "0.2.0"
clap = { version = "4.5.21", features = ["derive"] }
gcd = "2.3.0"
regex = "1.11.1"
